// GENERATED by scripts/generate-alarm-constants.mjs — do not edit.
export const ALARM_ENGINE_VERSION = 3;
export const DEFAULT_GRACE_MINUTES = 45;
export const MAX_RING_MINUTES = 60;
export const ALLOWED_DURATIONS = [7,14,30] as const;
